apiVersion: v1
kind: PersistentVolume
metadata:
  name: prowlarr-config-volume
spec:
  capacity:
    storage: 512Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    volumeHandle: prowlarr-config-volume

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config-claim
  namespace: services
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 512Mi
  volumeName: prowlarr-config-volume
