apiVersion: v1
kind: PersistentVolume
metadata:
  name: audiobookshelf-config-volume
spec:
  capacity:
    storage: 512Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    volumeHandle: audiobookshelf-config-volume

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-config-claim
  namespace: services
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 512Mi
  volumeName: audiobookshelf-config-volume

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: audiobookshelf-metadata-volume
spec:
  capacity:
    storage: 512Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    volumeHandle: audiobookshelf-metadata-volume

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-metadata-claim
  namespace: services
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 512Mi
  volumeName: audiobookshelf-metadata-volume
