apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rundeck-ingress
  namespace: services
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`rundeck.test.local.hohepa.dev`)
      kind: Rule
      services:
        - name: rundeck
          port: 4440
  tls:
    secretName: test-local-hohepa-dev-tls
