apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-data-volume
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    volumeHandle: minio-data-volume

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data-claim
  namespace: minio
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
  volumeName: minio-data-volume
