repositories:
- name: tailscale
  url: https://pkgs.tailscale.com/helmcharts

releases:
- name: tailscale-operator
  namespace: tailscale
  chart: tailscale/tailscale-operator
  values:
  - "./values.yaml"
