kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: calibre-web-claim
  namespace: services
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
