apiVersion: v1
kind: PersistentVolume
metadata:
  name: calibre-web-config-volume
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    volumeHandle: calibre-web-config-volume

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-web-config-claim
  namespace: services
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
  volumeName: calibre-web-config-volume
