apiVersion: v1
kind: PersistentVolume
metadata:
  name: bazarr-config-volume
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    volumeHandle: bazarr-config-volume

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config-claim
  namespace: services
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
  volumeName: bazarr-config-volume
