apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-config-volume
spec:
  capacity:
    storage: 512Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    volumeHandle: home-assistant-config-volume

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config-claim
  namespace: services
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 512Mi
  volumeName: home-assistant-config-volume

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-time-volume
spec:
  capacity:
    storage: 1Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /etc/localtime
  claimRef:
    name: home-assistant-time-claim
    namespace: services

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-time-claim
  namespace: services
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 1Mi
