apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sonarr-ingress
  namespace: services
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`sonarr.test.local.hohepa.dev`)
      kind: Rule
      services:
        - name: sonarr
          port: 8989
  tls:
    secretName: test-local-hohepa-dev-tls
