apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config-volume
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    volumeHandle: jellyfin-config-volume

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-claim
  namespace: services
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
  volumeName: jellyfin-config-volume

---  
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media-volume
spec:
  capacity:
    storage: 2.5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    volumeHandle: jellyfin-media-volume

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media-claim
  namespace: services
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 2.5Gi
  volumeName: jellyfin-media-volume
