repositories:
- name: jameswynn 
  url: http://jameswynn.github.io/helm-charts

releases:
- name: homepage
  namespace: services
  chart: jameswynn/homepage
  version: "2.1.0"
  values:
  - "./values.yaml"
