apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: deco-admin
  namespace: services
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`deco-admin.local.hohepa.dev`)
      kind: Rule
      services:
        - name: deco-admin
          port: 80
  tls:
    secretName: local-hohepa-dev-tls

---
apiVersion: v1
kind: Service
metadata:
  name: deco-admin
  namespace: services
spec:
  type: ExternalName
  ports:
  - name: http
    port: 80
  externalName: 192.168.68.1
