apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: selfsigned
  namespace: services
spec:
  insecureSkipVerify: true

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: proxmox-tane-mahuta
  namespace: services
  annotations:
    kubernetes.io/ingress.class: traefik-external
    gethomepage.dev/enabled: "true"
    gethomepage.dev/href: https://proxmox-tane-mahuta.local.hohepa.dev
    gethomepage.dev/group: Infra
    gethomepage.dev/name: Proxmox - Tane Mahuta
    gethomepage.dev/icon: proxmox.png
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`proxmox-tane-mahuta.local.hohepa.dev`)
    kind: Rule
    services:
    - name: proxmox-tane-mahuta
      port: 443
      scheme: https
      serversTransport: selfsigned

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: proxmox-tangaroa
  namespace: services
  annotations:
    kubernetes.io/ingress.class: traefik-external
    gethomepage.dev/enabled: "true"
    gethomepage.dev/href: https://proxmox-tangaroa.local.hohepa.dev
    gethomepage.dev/group: Infra
    gethomepage.dev/name: Proxmox - Tangaroa
    gethomepage.dev/icon: proxmox.png
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`proxmox-tangaroa.local.hohepa.dev`)
    kind: Rule
    services:
    - name: proxmox-tangaroa
      port: 443
      scheme: https
      serversTransport: selfsigned

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: proxmox-tawhirimatea
  namespace: services
  annotations:
    kubernetes.io/ingress.class: traefik-external
    gethomepage.dev/enabled: "true"
    gethomepage.dev/href: https://proxmox-tawhirimatea.local.hohepa.dev
    gethomepage.dev/group: Infra
    gethomepage.dev/name: Proxmox - Tawhirimatea
    gethomepage.dev/icon: proxmox.png
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`proxmox-tawhirimatea.local.hohepa.dev`)
    kind: Rule
    services:
    - name: proxmox-tawhirimatea
      port: 443
      scheme: https
      serversTransport: selfsigned

---
apiVersion: v1
kind: Service
metadata:
  name: proxmox-tane-mahuta
  namespace: services
spec:
  ports:
    - name: http
      port: 443
      targetPort: 8006

---
apiVersion: v1
kind: Endpoints
metadata:
  name: proxmox-tane-mahuta
  namespace: services
subsets:
  - addresses:
      - ip: 192.168.50.11
    ports:
      - name: http
        port: 8006

---
apiVersion: v1
kind: Service
metadata:
  name: proxmox-tangaroa
  namespace: services
spec:
  ports:
    - name: http
      port: 443
      targetPort: 8006

---
apiVersion: v1
kind: Endpoints
metadata:
  name: proxmox-tangaroa
  namespace: services
subsets:
  - addresses:
      - ip: 192.168.50.12
    ports:
      - name: http
        port: 8006

---
apiVersion: v1
kind: Service
metadata:
  name: proxmox-tawhirimatea
  namespace: services
spec:
  ports:
    - name: http
      port: 443
      targetPort: 8006

---
apiVersion: v1
kind: Endpoints
metadata:
  name: proxmox-tawhirimatea
  namespace: services
subsets:
  - addresses:
      - ip: 192.168.50.13
    ports:
      - name: http
        port: 8006
