apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: proxmox
  namespace: services
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`proxmox.local.hohepa.dev`)
    kind: Rule
    services:
    - name: proxmox
      port: 443
      scheme: https
      serversTransport: selfsigned

---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: selfsigned
  namespace: services
spec:
  insecureSkipVerify: true

---
apiVersion: v1
kind: Service
metadata:
  name: proxmox
  namespace: services
spec:
  ports:
    - name: http
      port: 443
      targetPort: 8006

---
apiVersion: v1
kind: Endpoints
metadata:
  name: proxmox
  namespace: services
subsets:
  - addresses:
      - ip: 192.168.70.0
    ports:
      - name: http
        port: 8006
