apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: synology
  namespace: services
  annotations:
    kubernetes.io/ingress.class: traefik-external
    gethomepage.dev/enabled: "true"
    gethomepage.dev/href: https://synology.local.hohepa.dev
    gethomepage.dev/group: Internal
    gethomepage.dev/name: Synology
    gethomepage.dev/icon: synology-dsm.png
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`synology.local.hohepa.dev`)
      kind: Rule
      services:
        - name: synology
          port: 5000
  tls:
    secretName: local-hohepa-dev-tls

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: synology-syncthing
  namespace: services
  annotations:
    kubernetes.io/ingress.class: traefik-external
    gethomepage.dev/enabled: "true"
    gethomepage.dev/href: https://synology-syncthing.local.hohepa.dev
    gethomepage.dev/group: Internal
    gethomepage.dev/name: Synology Syncthing
    gethomepage.dev/icon: syncthing.png
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`synology-syncthing.local.hohepa.dev`)
      kind: Rule
      services:
        - name: synology-syncthing
          port: 8384
  tls:
    secretName: local-hohepa-dev-tls

---
apiVersion: v1
kind: Service
metadata:
  name: synology
  namespace: services
spec:
  type: ExternalName
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  externalName: 192.168.50.50

---
apiVersion: v1
kind: Service
metadata:
  name: synology-syncthing
  namespace: services
spec:
  type: ExternalName
  ports:
  - name: http
    port: 8384
    targetPort: 8384
  externalName: 192.168.50.50
