apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: unifi
  namespace: services
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`unifi.local.hohepa.dev`)
      kind: Rule
      services:
        - name: unifi
          port: 443
  tls:
    secretName: local-hohepa-dev-tls

---
apiVersion: v1
kind: Service
metadata:
  name: unifi
  namespace: services
spec:
  type: ExternalName
  ports:
  - name: https
    port: 443
  externalName: 192.168.0.1
