apiVersion: v1
kind: PersistentVolume
metadata:
  name: tdarr-config-volume
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    volumeHandle: tdarr-config-volume

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-config-claim
  namespace: services
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
  volumeName: tdarr-config-volume

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tdarr-server-volume
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    volumeHandle: tdarr-server-volume

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-server-claim
  namespace: services
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
  volumeName: tdarr-server-volume
