apiVersion: v1
kind: PersistentVolume
metadata:
  name: uptime-kuma-data-volume
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    volumeHandle: uptime-kuma-data-volume

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-data-claim
  namespace: services
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
  volumeName: uptime-kuma-data-volume
