apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma
  namespace: services
spec:
  selector:
    matchLabels:
      app: uptime-kuma
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      containers:
      - name: uptime-kuma
        image: louislam/uptime-kuma:1
        env:
        - name: UPTIME_KUMA_PORT
          value: "3001"
        ports: 
          - containerPort: 3001
        volumeMounts:
        - mountPath: /app/data
          name: uptime-kuma-data
      volumes:
      - name: uptime-kuma-data
        persistentVolumeClaim:
          claimName:  uptime-kuma-data-claim
