apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: example
  namespace: default
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: external-secrets-example
    template:
      engineVersion: v2
      metadata:
        annotations:
          foo: "bar"
  data:
  - secretKey: foo
    remoteRef:
      key: "foo"
