apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-dashboard
  namespace: longhorn
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`longhorn.local.hohepa.dev`)
      kind: Rule
      services:
        - name: longhorn-frontend
          port: 80
  tls:
    secretName: local-hohepa-dev-tls
