apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgadmin-config-volume
spec:
  capacity:
    storage: 512Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    volumeHandle: pgadmin-config-volume

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-config-claim
  namespace: cnpg-system
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 512Mi
  volumeName: pgadmin-config-volume
