apiVersion: v1
kind: PersistentVolume
metadata:
  name: homebox-data-volume
spec:
  capacity:
    storage: 512Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    volumeHandle: homebox-data-volume

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebox-data-claim
  namespace: services
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 512Mi
  volumeName: homebox-data-volume
