apiVersion: v1
kind: PersistentVolume
metadata:
  name: readarr-config-volume
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    volumeHandle: readarr-config-volume

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: readarr-config-claim
  namespace: services
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
  volumeName: readarr-config-volume
