apiVersion: v1
kind: PersistentVolume
metadata:
  name: tandoor-media-volume
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    volumeHandle: tandoor-media-volume

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tandoor-media-claim
  namespace: services
  labels:
    app: recipes
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: tandoor-media-volume


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tandoor-static-volume
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    volumeHandle: tandoor-static-volume
 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tandoor-static-claim
  namespace: services
  labels:
    app: recipes
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: tandoor-static-volume


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tandoor-postgresql-data-volume
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    volumeHandle: tandoor-postgresql-data-volume

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tandoor-postgresql-data-claim
  namespace: services
  labels:
    app: recipes
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  volumeName: tandoor-postgresql-data-volume
