apiVersion: v1
data:
  username: cmFkYXJy
  password: cmFkYXJy
kind: Secret
metadata:
  name: radarr-db
  namespace: services
type: kubernetes.io/basic-auth

---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: radarr-db
  namespace: services
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: enabled
spec:
  instances: 1
  bootstrap:
    # initdb:
    #   owner: radarr
    #   secret:
    #     name: radarr-db
    recovery:
      source: radarr-db-backup
      owner: radarr
      secret:
        name: radarr-db

  backup:
    barmanObjectStore:
      destinationPath: "s3://cloudnative-pg-backups/"
      endpointURL: "http://minio.minio.svc.cluster.local:9000"
      s3Credentials:
        accessKeyId:
          name: minio-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: minio-creds
          key: ACCESS_SECRET_KEY
      wal:
        compression: bzip2
      data:
        compression: bzip2
    retentionPolicy: "2d"

  storage:
    size: 2Gi

  externalClusters:
    - name: radarr-db-backup
      barmanObjectStore:
        serverName: radarr-db
        destinationPath: "s3://cloudnative-pg-backups/"
        endpointURL: "http://minio.minio.svc.cluster.local:9000"
        s3Credentials:
          accessKeyId:
            name: minio-creds
            key: ACCESS_KEY_ID
          secretAccessKey:
            name: minio-creds
            key: ACCESS_SECRET_KEY

---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: radarr-main
  namespace: services
spec:
  name: radarr-main
  owner: radarr
  cluster:
    name: radarr-db

---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: radarr-log
  namespace: services
spec:
  name: radarr-log
  owner: radarr
  cluster:
    name: radarr-db